name: twsnmpfm
description: TWSNMP for Mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.0+6

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.1
  intl: ^0.18.1
  shared_preferences: ^2.0.15
  test: ^1.21.1
  flutter_riverpod: ^2.4.5
  regexed_validator: ^2.0.0+1
  dart_ping_ios: ^4.0.2
  dart_snmp: ^3.0.1
  statistics: ^1.0.20
  ml_algo: ^16.13.0
  dart_ping: ^9.0.1
  sprintf: ^7.0.0
  p5: ^0.1.0
  basic_utils: ^5.7.0
  flutter_beep: ^1.0.0
  ntp: ^2.0.0
  udp: ^5.0.3
  mailer: ^6.0.1
  flutter_simple_treeview: ^3.0.1
  fl_chart: ^0.64.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/conf/mib.txt
    - assets/conf/services.txt
    - assets/conf/mac-vendors-export.csv

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/images/twsnmpfm.png"
