name: twsnmpfm
description: TWSNMP for Mobile

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.3.0+4

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.9.3
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  test: ^1.21.1
  flutter_riverpod: ^1.0.4
  regexed_validator: ^2.0.0+1
  dart_ping_ios: ^1.1.0
  dart_snmp: ^2.0.0
  statistics: ^1.0.20
  ml_algo: ^16.13.0
  charts_flutter: ^0.12.0
  dart_ping: ^6.1.2
  sprintf: ^6.0.0
  p5: ^0.1.0
  google_mobile_ads: ^1.2.0
  basic_utils: ^4.4.1
  flutter_beep: ^1.0.0
  ntp: ^2.0.0
  udp: ^5.0.3
  mailer: ^5.2.0
  flutter_simple_treeview: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  generate: true
  assets:
    - assets/conf/mib.txt
    - assets/conf/services.txt
    - assets/conf/mac-vendors-export.csv

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "lib/assets/images/twsnmpfm.png"
